services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: ${POSTGRES_CONTAINER_NAME:-alexandro-mex-postgres}
    restart: on-failure:5
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  #redis:
  #  env_file: .env
  #  image: redis:8.2.2-bookworm@sha256:4521b581dbddea6e7d81f8fe95ede93f5648aaa66a9dacd581611bf6fe7527bd
  #  container_name: ${REDIS_CONTAINER_NAME:-redis}
  #  restart: on-failure:5
  #  command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}", "--bind", "0.0.0.0", "--port", "${REDIS_PORT:-6379}"]
  #  ports:
  #    - ${REDIS_PORT:-6379}:6379
  #  volumes:
  #    - ./redis.conf:/redis.conf
  #    - redis_data:/data
    # networks:
    #   - app-network
  #  healthcheck:
  #    test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
  #    interval: 10s
  #    timeout: 5s
  #    retries: 5
  #    start_period: 5s

  #app:
  #  container_name: alexandro-mex-backend
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  command: sh -c "npx prisma generate && npm run start:dev"
  #  env_file: .env
  #  environment:
  #    - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public
  #  restart: on-failure:5
  #  depends_on:
  #    postgres:
  #     condition: service_healthy
  #    redis:
  #      condition: service_healthy
  #  ports:
  #    - "${APP_PORT:-3001}:3001"
  #  volumes:
  #    - ./src:/app/src           
  #    - ./prisma:/app/prisma   
  #    - ./.env:/app/.env    
  #    - /app/node_modules    
  #    - backend_uploads:/app/uploads

volumes:
  postgres_data:
    driver: local
  #backend_uploads:
  #  driver: local

# networks:
#   app-network:
#     driver: bridge