export const YEAR_MONTH_REGEX = /^\d{4}-(0[1-9]|1[0-2])$/
export const PASSWORD_REGEX = /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#]).+$/
export const INNER_SPACES_REGEX = /^\S+$/
export const SQL_IDENTIFIER_REGEX = /^[a-zA-Z_][a-zA-Z0-9_]*$/
export const TOKEN_DURATION_REGEX = /^(?:[1-9]\d*(?:[ywdhms]))+$/i
export const UPPERCASE_PASSWORD_CHARACTERS_REGEX = /[A-Z]/
export const LOWERCASE_PASSWORD_CHARACTERS_REGEX = /[a-z]/
export const PASSWORD_DIGIT_REGEX = /[0-9]/
export const PASSWORD_SPECIAL_CHARACTER_REGEX = /[\W_]/
